server:
    port: 8081
    
spring:
    datasource:
        diriver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://14.63.166.136:3306/test3?useLocalSessionState=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: pandora_ojt
        password: 1234
    devtools: # devtools
        livereload:
            enabled: true # view 단 바뀔 시 적용
        restart:
            enabled: true # controller, model 변경 시 적용

mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.rlest.domain
    configuration:
        map-underscore-to-camel-case: true